apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/control-deployment.yaml
  - manifests/sensor-deployment.yaml
  - manifests/reporting-deployment.yaml
  - manifests/networkpolicy-restrict.yaml
  - manifests/rbac.yaml
  - manifests/psp-or-pss.yaml
