apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-only
  namespace: agua-inteligente
spec:
  podSelector:
    matchLabels:
      app: reporting
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: proxy
