name: Apply with approval

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init & Plan
        working-directory: iac
        run: |
          terraform init -input=false
          terraform plan -input=false -out=tfplan.binary
      - name: Upload Plan (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: iac/tfplan.binary

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
      - uses: actions/checkout@v4
      - name: Wait for manual approval
        uses: peter-evans/wait-for-approval@v2
        with:
          timeout_minutes: 120
      - name: Terraform Apply
        working-directory: iac
        run: terraform apply -input=false -auto-approve tfplan.binary
